package model;
// Generated Apr 19, 2019 1:41:01 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Colonne generated by hbm2java
 */
public class Colonne  implements java.io.Serializable {


     private Integer idColonne;
     private Projet projet;
     private String titre;
     private byte limiteTache;
     private String description;
     private Set taches = new HashSet(0);

    public Colonne() {
    }

	
    public Colonne(Projet projet, String titre, byte limiteTache, String description) {
        this.projet = projet;
        this.titre = titre;
        this.limiteTache = limiteTache;
        this.description = description;
    }
    public Colonne(Projet projet, String titre, byte limiteTache, String description, Set taches) {
       this.projet = projet;
       this.titre = titre;
       this.limiteTache = limiteTache;
       this.description = description;
       this.taches = taches;
    }
   
    public Integer getIdColonne() {
        return this.idColonne;
    }
    
    public void setIdColonne(Integer idColonne) {
        this.idColonne = idColonne;
    }
    public Projet getProjet() {
        return this.projet;
    }
    
    public void setProjet(Projet projet) {
        this.projet = projet;
    }
    public String getTitre() {
        return this.titre;
    }
    
    public void setTitre(String titre) {
        this.titre = titre;
    }
    public byte getLimiteTache() {
        return this.limiteTache;
    }
    
    public void setLimiteTache(byte limiteTache) {
        this.limiteTache = limiteTache;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getTaches() {
        return this.taches;
    }
    
    public void setTaches(Set taches) {
        this.taches = taches;
    }




}


