package model;
// Generated Apr 19, 2019 1:41:01 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Commentaire generated by hbm2java
 */
public class Commentaire  implements java.io.Serializable {


     private Integer idCommentaire;
     private Tache tache;
     private Utilisateur utilisateur;
     private String commentaire;
     private Date dateCreation;
     private Date dateModification;

    public Commentaire() {
    }

    public Commentaire(Tache tache, Utilisateur utilisateur, String commentaire, Date dateCreation, Date dateModification) {
       this.tache = tache;
       this.utilisateur = utilisateur;
       this.commentaire = commentaire;
       this.dateCreation = dateCreation;
       this.dateModification = dateModification;
    }
   
    public Integer getIdCommentaire() {
        return this.idCommentaire;
    }
    
    public void setIdCommentaire(Integer idCommentaire) {
        this.idCommentaire = idCommentaire;
    }
    public Tache getTache() {
        return this.tache;
    }
    
    public void setTache(Tache tache) {
        this.tache = tache;
    }
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }
    public String getCommentaire() {
        return this.commentaire;
    }
    
    public void setCommentaire(String commentaire) {
        this.commentaire = commentaire;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }
    
    public void setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }
    public Date getDateModification() {
        return this.dateModification;
    }
    
    public void setDateModification(Date dateModification) {
        this.dateModification = dateModification;
    }




}


