package model;
// Generated Apr 19, 2019 1:41:01 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Fichier generated by hbm2java
 */
public class Fichier  implements java.io.Serializable {


     private Integer idFichier;
     private Tache tache;
     private Utilisateur utilisateur;
     private String nomFichier;
     private String chemin;
     private String type;
     private int size;
     private Date dateCreation;

    public Fichier() {
    }

    public Fichier(Tache tache, Utilisateur utilisateur, String nomFichier, String chemin, String type, int size, Date dateCreation) {
       this.tache = tache;
       this.utilisateur = utilisateur;
       this.nomFichier = nomFichier;
       this.chemin = chemin;
       this.type = type;
       this.size = size;
       this.dateCreation = dateCreation;
    }
   
    public Integer getIdFichier() {
        return this.idFichier;
    }
    
    public void setIdFichier(Integer idFichier) {
        this.idFichier = idFichier;
    }
    public Tache getTache() {
        return this.tache;
    }
    
    public void setTache(Tache tache) {
        this.tache = tache;
    }
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }
    public String getNomFichier() {
        return this.nomFichier;
    }
    
    public void setNomFichier(String nomFichier) {
        this.nomFichier = nomFichier;
    }
    public String getChemin() {
        return this.chemin;
    }
    
    public void setChemin(String chemin) {
        this.chemin = chemin;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public int getSize() {
        return this.size;
    }
    
    public void setSize(int size) {
        this.size = size;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }
    
    public void setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }




}


