package model;
// Generated Apr 19, 2019 1:41:01 AM by Hibernate Tools 3.6.0



/**
 * GroupeAUtilisateur generated by hbm2java
 */
public class GroupeAUtilisateur  implements java.io.Serializable {


     private GroupeAUtilisateurId id;
     private Groupe groupe;
     private Utilisateur utilisateur;

    public GroupeAUtilisateur() {
    }

    public GroupeAUtilisateur(GroupeAUtilisateurId id, Groupe groupe, Utilisateur utilisateur) {
       this.id = id;
       this.groupe = groupe;
       this.utilisateur = utilisateur;
    }
   
    public GroupeAUtilisateurId getId() {
        return this.id;
    }
    
    public void setId(GroupeAUtilisateurId id) {
        this.id = id;
    }
    public Groupe getGroupe() {
        return this.groupe;
    }
    
    public void setGroupe(Groupe groupe) {
        this.groupe = groupe;
    }
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }




}


