package model;
// Generated Apr 19, 2019 1:41:01 AM by Hibernate Tools 3.6.0



/**
 * GroupeAUtilisateurId generated by hbm2java
 */
public class GroupeAUtilisateurId  implements java.io.Serializable {


     private int idGroupe;
     private int idUtilisateur;

    public GroupeAUtilisateurId() {
    }

    public GroupeAUtilisateurId(int idGroupe, int idUtilisateur) {
       this.idGroupe = idGroupe;
       this.idUtilisateur = idUtilisateur;
    }
   
    public int getIdGroupe() {
        return this.idGroupe;
    }
    
    public void setIdGroupe(int idGroupe) {
        this.idGroupe = idGroupe;
    }
    public int getIdUtilisateur() {
        return this.idUtilisateur;
    }
    
    public void setIdUtilisateur(int idUtilisateur) {
        this.idUtilisateur = idUtilisateur;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GroupeAUtilisateurId) ) return false;
		 GroupeAUtilisateurId castOther = ( GroupeAUtilisateurId ) other; 
         
		 return (this.getIdGroupe()==castOther.getIdGroupe())
 && (this.getIdUtilisateur()==castOther.getIdUtilisateur());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdGroupe();
         result = 37 * result + this.getIdUtilisateur();
         return result;
   }   


}


