package model;
// Generated Apr 19, 2019 1:41:01 AM by Hibernate Tools 3.6.0



/**
 * ProjetAGroupe generated by hbm2java
 */
public class ProjetAGroupe  implements java.io.Serializable {


     private ProjetAGroupeId id;
     private Groupe groupe;
     private Projet projet;

    public ProjetAGroupe() {
    }

    public ProjetAGroupe(ProjetAGroupeId id, Groupe groupe, Projet projet) {
       this.id = id;
       this.groupe = groupe;
       this.projet = projet;
    }
   
    public ProjetAGroupeId getId() {
        return this.id;
    }
    
    public void setId(ProjetAGroupeId id) {
        this.id = id;
    }
    public Groupe getGroupe() {
        return this.groupe;
    }
    
    public void setGroupe(Groupe groupe) {
        this.groupe = groupe;
    }
    public Projet getProjet() {
        return this.projet;
    }
    
    public void setProjet(Projet projet) {
        this.projet = projet;
    }




}


