package model;
// Generated Apr 19, 2019 1:41:01 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * ProjetActivite generated by hbm2java
 */
public class ProjetActivite  implements java.io.Serializable {


     private Integer idActivite;
     private Tache tache;
     private Utilisateur utilisateur;
     private Projet projet;
     private Date dateCreation;

    public ProjetActivite() {
    }

    public ProjetActivite(Tache tache, Utilisateur utilisateur, Projet projet, Date dateCreation) {
       this.tache = tache;
       this.utilisateur = utilisateur;
       this.projet = projet;
       this.dateCreation = dateCreation;
    }
   
    public Integer getIdActivite() {
        return this.idActivite;
    }
    
    public void setIdActivite(Integer idActivite) {
        this.idActivite = idActivite;
    }
    public Tache getTache() {
        return this.tache;
    }
    
    public void setTache(Tache tache) {
        this.tache = tache;
    }
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }
    public Projet getProjet() {
        return this.projet;
    }
    
    public void setProjet(Projet projet) {
        this.projet = projet;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }
    
    public void setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }




}


