package model;
// Generated Apr 19, 2019 1:41:01 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Projet generated by hbm2java
 */
public class Projet  implements java.io.Serializable {


     private Integer idProjet;
     private String nomProjet;
     private String email;
     private boolean estPublique;
     private String description;
     private String responsable;
     private Date dateDebut;
     private Date dateFin;
     private byte priorites;
     private Set tags = new HashSet(0);
     private Set colonnes = new HashSet(0);
     private Set projetActivites = new HashSet(0);
     private Set taches = new HashSet(0);
     private Set projetAGroupes = new HashSet(0);

    public Projet() {
    }

	
    public Projet(String nomProjet, String email, boolean estPublique, String description, String responsable, Date dateDebut, Date dateFin, byte priorites) {
        this.nomProjet = nomProjet;
        this.email = email;
        this.estPublique = estPublique;
        this.description = description;
        this.responsable = responsable;
        this.dateDebut = dateDebut;
        this.dateFin = dateFin;
        this.priorites = priorites;
    }
    public Projet(String nomProjet, String email, boolean estPublique, String description, String responsable, Date dateDebut, Date dateFin, byte priorites, Set tags, Set colonnes, Set projetActivites, Set taches, Set projetAGroupes) {
       this.nomProjet = nomProjet;
       this.email = email;
       this.estPublique = estPublique;
       this.description = description;
       this.responsable = responsable;
       this.dateDebut = dateDebut;
       this.dateFin = dateFin;
       this.priorites = priorites;
       this.tags = tags;
       this.colonnes = colonnes;
       this.projetActivites = projetActivites;
       this.taches = taches;
       this.projetAGroupes = projetAGroupes;
    }
   
    public Integer getIdProjet() {
        return this.idProjet;
    }
    
    public void setIdProjet(Integer idProjet) {
        this.idProjet = idProjet;
    }
    public String getNomProjet() {
        return this.nomProjet;
    }
    
    public void setNomProjet(String nomProjet) {
        this.nomProjet = nomProjet;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public boolean isEstPublique() {
        return this.estPublique;
    }
    
    public void setEstPublique(boolean estPublique) {
        this.estPublique = estPublique;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getResponsable() {
        return this.responsable;
    }
    
    public void setResponsable(String responsable) {
        this.responsable = responsable;
    }
    public Date getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }
    public Date getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }
    public byte getPriorites() {
        return this.priorites;
    }
    
    public void setPriorites(byte priorites) {
        this.priorites = priorites;
    }
    public Set getTags() {
        return this.tags;
    }
    
    public void setTags(Set tags) {
        this.tags = tags;
    }
    public Set getColonnes() {
        return this.colonnes;
    }
    
    public void setColonnes(Set colonnes) {
        this.colonnes = colonnes;
    }
    public Set getProjetActivites() {
        return this.projetActivites;
    }
    
    public void setProjetActivites(Set projetActivites) {
        this.projetActivites = projetActivites;
    }
    public Set getTaches() {
        return this.taches;
    }
    
    public void setTaches(Set taches) {
        this.taches = taches;
    }
    public Set getProjetAGroupes() {
        return this.projetAGroupes;
    }
    
    public void setProjetAGroupes(Set projetAGroupes) {
        this.projetAGroupes = projetAGroupes;
    }




}


