package model;
// Generated Apr 19, 2019 1:41:01 AM by Hibernate Tools 3.6.0



/**
 * ProjetAGroupeId generated by hbm2java
 */
public class ProjetAGroupeId  implements java.io.Serializable {


     private int idGroupe;
     private int idProjet;

    public ProjetAGroupeId() {
    }

    public ProjetAGroupeId(int idGroupe, int idProjet) {
       this.idGroupe = idGroupe;
       this.idProjet = idProjet;
    }
   
    public int getIdGroupe() {
        return this.idGroupe;
    }
    
    public void setIdGroupe(int idGroupe) {
        this.idGroupe = idGroupe;
    }
    public int getIdProjet() {
        return this.idProjet;
    }
    
    public void setIdProjet(int idProjet) {
        this.idProjet = idProjet;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProjetAGroupeId) ) return false;
		 ProjetAGroupeId castOther = ( ProjetAGroupeId ) other; 
         
		 return (this.getIdGroupe()==castOther.getIdGroupe())
 && (this.getIdProjet()==castOther.getIdProjet());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdGroupe();
         result = 37 * result + this.getIdProjet();
         return result;
   }   


}


