package model;
// Generated Apr 19, 2019 1:41:01 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tache generated by hbm2java
 */
public class Tache  implements java.io.Serializable {


     private Integer idTache;
     private Colonne colonne;
     private Projet projet;
     private String titre;
     private String description;
     private Date dateCreation;
     private String responsable;
     private String createur;
     private Date dateDebut;
     private Date dateFin;
     private Date dateModification;
     private Date dateEstime;
     private Date dateDeplace;
     private byte priorite;
     private Set tacheATagsForIdTache = new HashSet(0);
     private Set projetActivites = new HashSet(0);
     private Set commentaires = new HashSet(0);
     private Set tacheATagsForIdTag = new HashSet(0);
     private Set fichiers = new HashSet(0);

    public Tache() {
    }

	
    public Tache(Colonne colonne, Projet projet, String titre, String description, Date dateCreation, String responsable, String createur, Date dateDebut, Date dateFin, Date dateModification, Date dateEstime, Date dateDeplace, byte priorite) {
        this.colonne = colonne;
        this.projet = projet;
        this.titre = titre;
        this.description = description;
        this.dateCreation = dateCreation;
        this.responsable = responsable;
        this.createur = createur;
        this.dateDebut = dateDebut;
        this.dateFin = dateFin;
        this.dateModification = dateModification;
        this.dateEstime = dateEstime;
        this.dateDeplace = dateDeplace;
        this.priorite = priorite;
    }
    public Tache(Colonne colonne, Projet projet, String titre, String description, Date dateCreation, String responsable, String createur, Date dateDebut, Date dateFin, Date dateModification, Date dateEstime, Date dateDeplace, byte priorite, Set tacheATagsForIdTache, Set projetActivites, Set commentaires, Set tacheATagsForIdTag, Set fichiers) {
       this.colonne = colonne;
       this.projet = projet;
       this.titre = titre;
       this.description = description;
       this.dateCreation = dateCreation;
       this.responsable = responsable;
       this.createur = createur;
       this.dateDebut = dateDebut;
       this.dateFin = dateFin;
       this.dateModification = dateModification;
       this.dateEstime = dateEstime;
       this.dateDeplace = dateDeplace;
       this.priorite = priorite;
       this.tacheATagsForIdTache = tacheATagsForIdTache;
       this.projetActivites = projetActivites;
       this.commentaires = commentaires;
       this.tacheATagsForIdTag = tacheATagsForIdTag;
       this.fichiers = fichiers;
    }
   
    public Integer getIdTache() {
        return this.idTache;
    }
    
    public void setIdTache(Integer idTache) {
        this.idTache = idTache;
    }
    public Colonne getColonne() {
        return this.colonne;
    }
    
    public void setColonne(Colonne colonne) {
        this.colonne = colonne;
    }
    public Projet getProjet() {
        return this.projet;
    }
    
    public void setProjet(Projet projet) {
        this.projet = projet;
    }
    public String getTitre() {
        return this.titre;
    }
    
    public void setTitre(String titre) {
        this.titre = titre;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }
    
    public void setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }
    public String getResponsable() {
        return this.responsable;
    }
    
    public void setResponsable(String responsable) {
        this.responsable = responsable;
    }
    public String getCreateur() {
        return this.createur;
    }
    
    public void setCreateur(String createur) {
        this.createur = createur;
    }
    public Date getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }
    public Date getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }
    public Date getDateModification() {
        return this.dateModification;
    }
    
    public void setDateModification(Date dateModification) {
        this.dateModification = dateModification;
    }
    public Date getDateEstime() {
        return this.dateEstime;
    }
    
    public void setDateEstime(Date dateEstime) {
        this.dateEstime = dateEstime;
    }
    public Date getDateDeplace() {
        return this.dateDeplace;
    }
    
    public void setDateDeplace(Date dateDeplace) {
        this.dateDeplace = dateDeplace;
    }
    public byte getPriorite() {
        return this.priorite;
    }
    
    public void setPriorite(byte priorite) {
        this.priorite = priorite;
    }
    public Set getTacheATagsForIdTache() {
        return this.tacheATagsForIdTache;
    }
    
    public void setTacheATagsForIdTache(Set tacheATagsForIdTache) {
        this.tacheATagsForIdTache = tacheATagsForIdTache;
    }
    public Set getProjetActivites() {
        return this.projetActivites;
    }
    
    public void setProjetActivites(Set projetActivites) {
        this.projetActivites = projetActivites;
    }
    public Set getCommentaires() {
        return this.commentaires;
    }
    
    public void setCommentaires(Set commentaires) {
        this.commentaires = commentaires;
    }
    public Set getTacheATagsForIdTag() {
        return this.tacheATagsForIdTag;
    }
    
    public void setTacheATagsForIdTag(Set tacheATagsForIdTag) {
        this.tacheATagsForIdTag = tacheATagsForIdTag;
    }
    public Set getFichiers() {
        return this.fichiers;
    }
    
    public void setFichiers(Set fichiers) {
        this.fichiers = fichiers;
    }




}


